### ISSUE TITLE
Bonds between atoms are appearing as thick black tubes

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#107]
How do I change the drawing style for covalent bonds back to the rendering style they had a few months ago?  They used to be thinner and grey so a user could see the atoms. Now they are thick and black and it's hard to see atoms.

<img width="853" alt="Screenshot 2023-05-12 at 1 26 33 PM" src="https://github.com/ncbi/icn3d/assets/6663433/468a6655-7e9f-4249-a6a0-b8c16a691292">

Here's the link:  https://structure.ncbi.nlm.nih.gov/icn3d/share.html?1akJ8aLKwEc3DZ9R6

**Comment by jiywang3** [comment]
It worked for me as shown below. You can use the menu "Style > Preference" to change the radius of sticks and balls. The black sticks is probably due to "EXT_frag_depth is NOT supported" in your browser. Could you specify the browser version and your computer model? What did you see in the console?
 
![image](https://github.com/ncbi/icn3d/assets/11690222/0770c29c-cf12-41f5-bb6c-55835f23a4ef)

**Comment by digitalbio** [comment]
Thanks for looking into this.  I just used the link to view it again and now it's working.  I guess I'll close the issue.
