### ISSUE TITLE
Save to PNG

### ISSUE THREAD

**Issue by MendesMarcus** [ncbi/icn3d#25]
When I tried to save the current canvas scene using the "iCn3D PNG Image", it generates two separate files (one .HTML and one .PNG). I read in the Readme that the function works that way. Unfortunately, google chrome has some issues with saving two files simultaneously because it asks for permission to download multiple files concurrently, and some users can have a problem seeing that. Lastly, when I opened the .html file and clicked on the link available in the image, it opened a new iCn3D tab and started loading the data, but it gets stuck.

**Comment by jiywang3** [comment]
Could you show the sharable link URL, which can be generated in the menu "File > Share Link"? Probably the sharable link had some problem.

**Comment by MendesMarcus** [comment]
https://structure.ncbi.nlm.nih.gov/icn3d/share.html?6mvP1mh8aV2qhbFk6

**Comment by jiywang3** [comment]
Somehow the full command has an invalid command "dist | selected;". I fixed iCn3D so that it can tolerate this command.
https://www.ncbi.nlm.nih.gov/Structure/icn3d/full.html?shownote=1&divid=div0&mmdbid=3qeq&date=20210405&v=2.24.7&command=pickatom 5409; dist | selected selected; dist | selected selected; dist | selected; set lines off; window interaction table; set map 2fofc sigma 1.5; set mode all; set map 2fofc sigma 1.5; setoption map nothing; set map 2fofc sigma 4; set map 2fofc sigma 0.5
