### ISSUE TITLE
The Rainbow coloring in iCn3D isn't behaving correctly 

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#41]
The Rainbow coloring style should work in the following way - the amino terminus of each protein chain (or the 5' end of each nucleic acid chain) should be red and the carboxyl terminus (or 3' end) should be violet.  

When colored correctly, a structure like 1IGY will show the amino ends of all four chains in red. 

Each chain needs to be colored independently because each chain is a separate molecule.

Instead it looks like the coloring is treating the four chains as part of a single concatenated molecule.

**Comment by digitalbio** [comment]
This image shows how the ends of each chain in the structure should be colored and how the amino ends of each sequence should be colored.

![IMG_67A5469A4445-1](https://user-images.githubusercontent.com/6663433/131912500-157a8306-9155-4ee2-8a4e-eb8f4caa0cfb.jpeg)

**Comment by jiywang3** [comment]
The rainbow coloring is for any selection. What you can do is to select each chain and apply the rainbow coloring. Here is the share link of my example: https://structure.ncbi.nlm.nih.gov/icn3d/share.html?uqzXVbUSoxbLJocW8
![image](https://user-images.githubusercontent.com/11690222/131914177-62538332-9303-4bb9-98ee-e0784410c253.png)

**Comment by digitalbio** [comment]
No, that doesn't make sense.  If I use other coloring styles, I see the coloring applied to the entire protein.  For example, I can color a protein by charge without selecting each chain.

In a protein, each chain is independent, so each chain must be colored from the amino end to the carboxyl end.  

PDB does this correctly with jsmol.  Cn3D does this correctly also.

**Comment by jiywang3** [comment]
The fundamental design of iCn3D is to apply features only to the selection. Different users have different preferences. This way you can apply Rainbow coloring to any of your selection and make it more flexible.

**Comment by digitaltodd** [comment]
The fundamental design is good. The issue is related to global selections. 

There are two way to apply a style to an entire structure: have nothing selected or select all atoms. This works for all of the styles. 

In the case of rainbow and spectrum the issue is that the global style is being applied incorrectly, and the information is misleading. Let's use 1NAJ, a DNA structure as an example. When either spectrum or rainbow are applied they are applied to the both stands as if the strands were one molecule. 

As spectrum and rainbow are intended to show the order of residues, the global coloring needs to be set on each chain independently - like chain coloring. Imagine if you has to apply each chain color independently ... what a pain, some structures have 10's and 100's of chains. 

![Screen Shot 2021-09-03 at 10 39 11 AM](https://user-images.githubusercontent.com/6664990/132046424-6f01b0c5-c9f2-49bb-9c3d-7ca4137801fd.png)
![Screen Shot 2021-09-03 at 10 40 12 AM](https://user-images.githubusercontent.com/6664990/132046434-36fa7bfa-7166-4567-8bb9-c2fc9b8f8278.png)


![Screen Shot 2021-09-03 at 10 38 22 AM](https://user-images.githubusercontent.com/6664990/132046023-182b4b07-d9ee-467f-87ff-8d69272d52bf.png)

**Comment by jiywang3** [comment]
I could add two options for Rainbow: per Selection, and per Chain in the next release.

**Comment by jiywang3** [comment]
The feature is available now.
