### ISSUE TITLE
Problem with viewing structures side by side

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#82]
Structure files:  1HZH, 1IGY

1.  Load files
2. Click View > Side by side 

problem:  the structures are not displayed

**Comment by jiywang3** [comment]
The bug was fixed/ You can try this link: https://www.ncbi.nlm.nih.gov/Structure/icn3d/full2.html?mmdbafid=1HZH,1IGY&bu=0&date=20220714&v=3.12.7&command=set%20mode%20all|||{%22factor%22:%221.000%22,%22mouseChange%22:{%22x%22:%220.000%22,%22y%22:%220.000%22},%22quaternion%22:{%22_x%22:%220.000%22,%22_y%22:%220.000%22,%22_z%22:%220.000%22,%22_w%22:%221.000%22}}&closepopup=1

**Comment by digitalbio** [comment]
I see them now.  Thanks!
